version: 0.0.0.{build}-beta
image: Visual Studio 2017
configuration: Release
install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.0,android-26,android-25,extra-google-m2repository,extra-android-m2repository
  # on windows we need to accept sublicenses for the new tooling, wee. 30 is an arbitrary number,
  # but should be the maximum number of licenses we explicitly need to type "Y ENTER" for.
  # also, the sdkmanager in all its glory leaks a bit of output to stderr, and powershell
  # and appveyor interpret that as errors, and blows up. so, when piping in our "Y ENTER"
  # responses, we invoke cmd so we can redirect stderr to stdout, and tell it to --update itself.
  - ps: for($i=0;$i -lt 30;$i++) { $response += "y`n"}; $response | cmd /c 'C:\android\tools\bin\sdkmanager.bat 2>&1' --update
build_script:
- cmd: >-
    powershell .\build.ps1 -Target Default -Verbosity diagnostic
artifacts:
- path: ./build/*.nupkg
  name: NuGet